id: 5e74e69a-7e31-4769-ad6a-c438fce816dc
alias: "00 🔧 Notifactions for new HA version"
mode: single
max_exceeded: silent
trigger:
  - platform: template
    value_template: >
      {%-  
        if not states('sensor.latest_stable') in ['unavailable', 'unknown' ] 
        and not states('sensor.current version') in ['unavailable', 'unknown' ]
      %}
        {%-  set c = states('sensor.current_version').split('.') %}
        {%-  set yc = c[0] | int %}
        {%-  set mc = c[1] | int %}
        {%-  set vc = c[2]  %}
        {%-  set l = states('sensor.latest_stable').split('.') %}
        {%-  set y = l[0] | int %}
        {%-  set m = l[1] | int %}
        {%-  set v = l[2] %}
        {{ (yc < y) | iif(true, (mc < m if yc == y else false) | iif(true, vc < v if mc == m else false) ) }}
      {%-  endif %}
    id: "stable"
  - platform: template
    value_template: >
      {%-  
        if not states('sensor.latest_beta') in ['unavailable', 'unknown' ] 
        and not states('sensor.current version') in ['unavailable', 'unknown' ]
      %}
        {%-  set c = states('sensor.current_version').split('.') %}
        {%-  set yc = c[0] | int %}
        {%-  set mc = c[1] | int %}
        {%-  set vc = c[2]  %}
        {%-  set l = states('sensor.latest_beta').split('.') %}
        {%-  set y = l[0] | int %}
        {%-  set m = l[1] | int %}
        {%-  set v = l[2] %}
        {{ (yc < y) | iif(true, (mc < m if yc == y else false) | iif(true, vc < v if mc == m else false)) }}
      {%-  endif %}
    id: "beta"
variables:
  current: "{{ states('sensor.current_version') }}"
  stable: "{{ states('sensor.latest_stable') }}"
  beta: "{{ states('sensor.latest_beta') }}"
action:
  - alias: "Dismiss old notification"
    service: persistent_notification.dismiss
    data:
      notification_id: ha_update
  - alias: "Create persistant notification"
    service: persistent_notification.create
    data:
      title: >
        {{ (trigger.id == 'beta') | iif('Beta update HA', 'Stable update HA') }}
      notification_id: ha_update
      message: >-
        Versie _{{ (trigger.id == 'beta') | iif(beta, stable) }}_ is nu beschikbaar. Je zit nu op _{{ current }}_.
        [Changelog](https://github.com/home-assistant/core/releases/tag/{{ (trigger.id == 'beta') | iif(beta, stable) }})
        {%- set b = states('sensor.potential_breaking_changes') | int %}
        {{ 
          ((b != 1) | iif('Er zijn ', 'Er is ') ~ (b == 0) | iif('geen', b) ~ ' breaking change' ~ (b != 1) | iif('s.', '. '))
          if trigger.id == 'stable'
        }}
  - alias: "Send notification to phone"
    service: notify.mobile_app_pixel_5
    data:
      title: >
        {{ (trigger.id == 'beta') | iif('Beta update HA', 'Stable update HA') }}
      message: >-
        Versie {{ (trigger.id == 'beta') | iif(beta, stable) }} is nu beschikbaar. Je zit nu op {{ current }}.
        {%- set b = states('sensor.potential_breaking_changes') | int %}
        {{ 
          ((b != 1) | iif('Er zijn ', 'Er is ') ~ (b == 0) | iif('geen', b) ~ ' breaking change' ~ (b != 1) | iif('s.', '. '))
          if trigger.id == 'stable'
        }}
      data:
        channel: Home Assistant
        ttl: 0
        priority: high
        actions:
          - action: "URI"
            title: "Changelog"
            uri: "https://github.com/home-assistant/core/releases/tag/{{ (trigger.id == 'beta') | iif(beta, stable) }}"
