id: e97b9673-d253-437f-9c85-7079a4c82305
alias: "00 🔧 Notifications HACS updates"
mode: single
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: not
    conditions:
      - alias: "HACS notification available?"
        condition: state
        entity_id: sensor.hacs
        state:
          - "unknown"
          - "unavailable"
action:
  - alias: "Dismiss old notifiaction"
    service: persistent_notification.dismiss
    data:
      notification_id: hacs_update
  - alias: "Are there updates?"
    choose:
      - conditions: "{{ not is_state('sensor.hacs', '0') }}"
        sequence:
          - alias: "Create new notification"
            service: persistent_notification.create
            data:
              title: "Updates HACS"
              notification_id: hacs_update
              message: >
                {%- for repo in state_attr(trigger.entity_id, 'repositories') %}
                  **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
                {%- endfor %}
