sensor:
  - unique_id: 16bc681e-f85f-4f43-91a0-96da3664bc66
    name: Location phone Marleen
    state: >-
      {%- if is_state('person.marleen', 'not_home') %}
        Niet thuis
      {%- elif not is_state('person.marleen', 'home') %}
        {{ states('person.marleen') }}
      {%- elif is_state('sensor.de_buurvrouw_bssid', '2c:3a:fd:bf:2c:fb') %}
        Zolder
      {%- elif is_state('sensor.de_buurvrouw_bssid', '2c:3a:fd:df:6d:a5') %}
        Eerste verdieping
      {%- 
        elif is_state('sensor.de_buurvrouw_bssid', '3c:a6:2f:f9:ee:c3') 
        or is_state('sensor.de_buurvrouw_bssid', '2c:91:ab:e6:1b:7c') 
      %}
        Beneden
      {%- else %}
        Thuis
      {%- endif %}
    picture: "/api/image/serve/e261093701adc6a0bd34e9c96b5feacb/512x512"

  - unique_id: 11fde20f-113c-4d69-9995-e4a7ca5dd45d
    name: Location phone Martijn
    state: >-
      {%- if is_state('person.martijn', 'not_home') %}
        Niet thuis
      {%- elif not is_state('person.martijn', 'home') %}
        {{ states('person.martijn') }}
      {%- elif is_state('sensor.pixel_5_wifi_bssid', '2c:3a:fd:bf:2c:fb') %}
        Zolder
      {%- elif is_state('sensor.pixel_5_wifi_bssid', '2c:3a:fd:df:6d:a5') %}
        Eerste verdieping
      {%- 
        elif is_state('sensor.pixel_5_wifi_bssid', '3c:a6:2f:f9:ee:c3') 
        or is_state('sensor.pixel_5_wifi_bssid', '2c:91:ab:e6:1b:7c') 
      %}
        Beneden
      {%- else %}
        Thuis
      {%- endif %}
    picture: "/api/image/serve/7dce8363a8fd22c90115bbada5ff395a/512x512"
