sensor:
  - unique_id: 9d6b50c5-6059-4d91-ae4e-43dcd095987c
    name: Rest en GFT
    state: >-
      {%- set sensor = 'sensor.afvalwijzer_restgft' %}
      {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
      {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
      {%- set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {%- if collection_date == 'unavailable' %}
        unavailable
      {%- elif (collection_date - now().date()).days == 0 %}
        Vandaag
      {%- elif (collection_date - now().date()).days == 1 %}
        Morgen
      {%- else %}
        {{ days[collection_date.weekday()] ~ ' ' ~ collection_date.strftime('%d-%m-%y') }}
      {%- endif %}
    icon: mdi:trash-can
    attributes:
      collection_date: >
        {%- set sensor = 'sensor.afvalwijzer_restgft' %}
        {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
        {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
        {{ collection_date }}

  - unique_id: 821b207c-5c06-4da4-9e8c-a5790e6e4c8c
    name: Papier en PMD
    state: >-
      {%- set sensor = 'sensor.afvalwijzer_dhm' %}
      {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
      {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
      {%- set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {%- if collection_date == 'unavailable' %}
        unavailable
      {%- elif (collection_date - now().date()).days == 0 %}
        Vandaag
      {%- elif (collection_date - now().date()).days == 1 %}
        Morgen
      {%- else %}
        {{ days[collection_date.weekday()] ~ ' ' ~ collection_date.strftime('%d-%m-%y') }}
      {%- endif %}
    icon: mdi:trash-can-outline
    attributes:
      collection_date: >
        {%- set sensor = 'sensor.afvalwijzer_dhm' %}
        {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
        {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
        {{ collection_date }}

  - unique_id: ff7c02aa-aea3-42a7-91f5-f1a8f88a8986
    name: Kerstboom
    state: >-
      {%- set sensor = 'sensor.afvalwijzer_kerstbomen' %}
      {%- set sensor = 'sensor.afvalwijzer_kerstbomen' %}
      {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
      {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
      {%- set days = ['Maandag', 'Dinsdag', 'Woensdag', 'Donderdag', 'Vrijdag', 'Zaterdag', 'Zondag' ] %}
      {%- if collection_date == 'unavailable' %}
        unavailable
      {%- elif (collection_date - now().date()).days == 0 %}
        Vandaag
      {%- elif (collection_date - now().date()).days == 1 %}
        Morgen
      {%- else %}
        {{ days[collection_date.weekday()] ~ ' ' ~ collection_date.strftime('%d-%m-%y') }}
      {%- endif %}
    icon: mdi:pine-tree
    attributes:
      collection_date: >
        {%- set sensor = 'sensor.afvalwijzer_kerstbomen' %}
        {%- set collection_date = state_attr(sensor, 'year_month_day_date') %}
        {%- set collection_date = as_local(as_datetime(collection_date)).date() if collection_date else 'unavailable' %}
        {{ collection_date }}
