trigger:
  - platform: state
    entity_id: person.martijn
    id: state_change
  - platform: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.person.martijn.last_changed)) / 60 > 10 }}"
    id: recent_change
  - platform: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.person.martijn.last_changed)) / 60 > (60 * 24) }}"
    id: extended_change
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_template_reloaded
sensor:
  - name: House state Martijn
    unique_id: ddcf1fc6-fd1d-465f-90c3-82818290595d
    state: >
      {%- set last_change_min = (as_timestamp(now()) - as_timestamp(states.person.martijn.last_changed)) / 60 %}
      {%- set person = 'person.martijn' %}
      {%- if last_change_min > (60*12) and is_state(person, 'not_home') %}
        Al lang niet thuis
      {%- elif last_change_min > 10 and is_state(person, 'not_home') %}
        Niet thuis
      {%- 
        elif (last_change_min > 10 and is_state(person, 'home')) 
        or (is_state(person, 'home') and is_state('sensor.huis_status_martijn', 'Just Left'))
      %}
        Thuis
      {%- elif is_state(person, 'home') %}
        Net thuis
      {%- elif is_state(person, 'not_home') %}
        Net weg
      {%- else %}
        {{ states(person) }}
      {%- endif %}
    icon: mdi:human-male
